# This is a config for E2B sandbox template.
# You can use template ID (fba2w2kbrhzusocdi5qj) or template name (vibe-nextjs-test__-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test__-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test__-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test__-3')

team_id = "6e774945-9a93-4113-945b-fc940185cc79"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test__-3"
template_id = "fba2w2kbrhzusocdi5qj"
