# This is a config for E2B sandbox template.
# You can use template ID (gnh6zy51yg62wzvq6y34) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("gnh6zy51yg62wzvq6y34") # Sync sandbox
# sandbox = await AsyncSandbox.create("gnh6zy51yg62wzvq6y34") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('gnh6zy51yg62wzvq6y34')

team_id = "6e774945-9a93-4113-945b-fc940185cc79"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_id = "gnh6zy51yg62wzvq6y34"
